### ISSUE TITLE
Wabbajack instalation stuck

### ISSUE THREAD

**Issue by beurp** [cacophony-wj/tSoD#1]
somewhere at Writing inlines files
The window is frozen but in the left i see they try to write <Ck output/textures/facemods/thepitt.esm/> around 0000B567_0.dds
and <Ck output/textures/facemods/unifficial fallout 3 patch.esm/> around 00002f42

Trying multiple times with the sames result

**Comment by cacophony-wj** [comment]
Double check to make certain your hard drive is not full. You need 100 GB free for the modlist, as well as about 30 GB for temp files on the drive where you have Wabbajack.exe, and maybe the same on the OS drive (usually C: for further temp files).

**Comment by cacophony-wj** [comment]
Closed due to lack of response.
